service: sandbox-sqs-serverless

frameworkVersion: ">=1.66.0 <2.0.0"

package:
  exclude:
    - .git/**
    - src/**
    - .*
    - tsconfig.*
    - package-lock.json
    - yarn.lock
    - README.md

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 128
  region: ap-northeast-1
  stage: dev
  environment:
    QUEUE_NAME: ${self:custom.QUEUE_NAME}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "sqs:sendMessage"
      Resource:
        - Fn::GetAtt:
            - MyQueue
            - Arn

custom:
  QUEUE_NAME: "my-queue"

resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:custom.QUEUE_NAME}

functions:
  publish:
    handler: dist/publish.handler
  subscribe:
    handler: dist/subscribe.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
